"""Add conversation support to Analysis model

Revision ID: e5a70a4bd6b5
Revises: e2971a14ea91
Create Date: 2025-05-20 10:49:25.011296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a70a4bd6b5'
down_revision = 'e2971a14ea91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_conversation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('messages', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.drop_column('messages')
        batch_op.drop_column('is_conversation')
        batch_op.drop_column('conversation_id')

    # ### end Alembic commands ###
